#!/bin/bash

apt update
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
apt-get update
apt-get install -y apt-transport-https
apt-get update
apt-get install -y dotnet-sdk-5.0
apt-get update
apt-get install -y apt-transport-https
apt-get update
apt-get install -y aspnetcore-runtime-5.0

apt install -y nginx

systemctl enable nginx
service nginx start

rm /etc/nginx/sites-available/default

echo 'server {
        listen        80;
        server_name   example.com *.example.com;
        location / {
                proxy_pass        http://127.0.0.1:5000;
                proxy_http_version 1.1;
                proxy_set_header   Upgrade $http_upgrade;
                proxy_set_header   Connection keep-alive;
                proxy_set_header   Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto $scheme;
        }
}' > /etc/nginx/sites-available/default

nginx -s reload

mkdir -p /var/www/webApi

echo '[Unit]
Description=Web API App running
[Service]
WorkingDirectory=/var/www/webApi
ExecStart=/usr/bin/dotnet /var/www/webApi/WebApi.dll
Restart=always
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=dotnet-example
User=root
Environment=ASPNETCORE_ENVIRONMENT=Production
Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
[Install]
WantedBy=multi-user.target' > /etc/systemd/system/dotnetapp.service

# After upload project WebApi.dll in /var/www/webApi
# systemctl enable dotnetapp.service
# systemctl start dotnetapp.service
# systemctl daemon-reload
#
# Diagnostics
#
# systemctl status dotnetapp.service
# nginx -t
